---
- name: Setup Apache Server
  hosts: aws_ec2
  become: true
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/project-key.pem"  # Path to private key
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes
